<template><div class="page-container"><FilterBar @search="onSearch" @reset="onReset"><a-input v-model:value="f.keyword" placeholder="姓名/手机号" allow-clear style="width:180px"/><a-select v-model:value="f.categoryId" placeholder="分类" allow-clear style="width:140px"><a-select-option v-for="c in categories" :key="c.id" :value="c.id">{{c.name}}</a-select-option></a-select></FilterBar><div class="page-card"><div class="page-header"><span class="page-title">联系人管理</span><a-button type="primary" @click="onCreate">新建联系人</a-button></div><DataTable :columns="cols" :data-source="list" :loading="ld" :total="t" v-model:page="p" v-model:page-size="ps"><template #a="{r}"><a-space><a @click="onEdit(r)">编辑</a><a @click="onDelete(r)" style="color:#ff4d4f">删除</a></a-space></template></DataTable></div><a-modal v-model:open="modalVisible" :title="editingId?'编辑联系人':'新建联系人'" @ok="onSubmit"><a-form layout="vertical"><a-form-item label="姓名" required><a-input v-model:value="form.name"/></a-form-item><a-form-item label="分类" required><a-select v-model:value="form.categoryId"><a-select-option v-for="c in categories" :key="c.id" :value="c.id">{{c.name}}</a-select-option></a-select></a-form-item><a-form-item label="电话"><a-input v-model:value="form.phone"/></a-form-item><a-form-item label="地址"><a-input v-model:value="form.address"/></a-form-item><a-form-item label="备注"><a-input v-model:value="form.remark"/></a-form-item></a-form></a-modal></div></template>
<script setup lang="ts">import {ref,reactive} from 'vue';import {message,Modal} from 'ant-design-vue';import {contactsApi} from '@/api/contacts';import FilterBar from '@/components/common/FilterBar.vue';import DataTable from '@/components/common/DataTable.vue'
const ld=ref(false),list=ref<any[]>([]),t=ref(0),p=ref(1),ps=ref(20);const f=reactive({keyword:'',categoryId:undefined as string|undefined})
const categories=ref<any[]>([])
const cols=[{title:'ID',dataIndex:'id',width:80},{title:'姓名',dataIndex:'name',width:120},{title:'分类',dataIndex:'categoryName',width:120},{title:'电话',dataIndex:'phone',width:130},{title:'地址',dataIndex:'address',width:180},{title:'备注',dataIndex:'remark',width:150},{title:'时间',dataIndex:'createdAt',width:160},{title:'操作',dataIndex:'action',width:120,slot:'a'}]
async function ft(){ld.value=true;try{const r=await contactsApi.getContactList({page:p.value,pageSize:ps.value,...f});list.value=r.data.data?.list||r.data?.list||[];t.value=r.data.data?.total||r.data?.total||0}catch{}finally{ld.value=false}}
async function fc(){const r=await contactsApi.getCategoryList({page:1,pageSize:100});categories.value=r.data.data?.list||r.data?.list||[]}
function onSearch(){p.value=1;ft()};function onReset(){f.keyword='';f.categoryId=undefined;onSearch()}
const modalVisible=ref(false),editingId=ref(''),form=reactive({name:'',categoryId:'',phone:'',address:'',remark:''})
function onCreate(){editingId.value='';form.name='';form.categoryId='';form.phone='';form.address='';form.remark='';modalVisible.value=true}
function onEdit(r:any){editingId.value=r.id;form.name=r.name;form.categoryId=r.categoryId;form.phone=r.phone||'';form.address=r.address||'';form.remark=r.remark||'';modalVisible.value=true}
async function onSubmit(){const data={...form};if(editingId.value){await contactsApi.updateContact(editingId.value,data)}else{await contactsApi.createContact(data)}message.success('保存成功');modalVisible.value=false;ft()}
async function onDelete(r:any){Modal.confirm({title:'确认删除',content:`确定删除「${r.name}」吗？`,onOk:async()=>{await contactsApi.deleteContact(r.id);message.success('已删除');ft()}})}
ft();fc();
</script>
