<template><div class="page-container"><FilterBar @search="onSearch" @reset="onReset"><a-input v-model:value="f.keyword" placeholder="社团名称" allow-clear style="width:180px"/><a-select v-model:value="f.status" placeholder="状态" allow-clear style="width:110px"><a-select-option value="active">正常</a-select-option><a-select-option value="banned">封禁</a-select-option></a-select></FilterBar><div class="page-card"><div class="page-header"><span class="page-title">社团列表</span><a-button type="primary" @click="onCreate">新建社团</a-button></div><DataTable :columns="cols" :data-source="list" :loading="ld" :total="t" v-model:page="p" v-model:page-size="ps"><template #cover="{r}"><a-image v-if="r.cover" :src="r.cover" :width="50" :height="50" style="object-fit:cover;border-radius:4px"/><span v-else>-</span></template><template #memberCount="{r}">{{r._count?.members||0}}</template><template #status="{r}"><a-tag :color="r.status==='active'?'green':'red'">{{r.status==='active'?'正常':'封禁'}}</a-tag></template><template #a="{r}"><a-space><a @click="$router.push('/club/members/'+r.id)">成员</a><a @click="onEdit(r)">编辑</a><a @click="onToggle(r)">{{r.status==='active'?'封禁':'解封'}}</a><a @click="onDelete(r)" style="color:#ff4d4f">删除</a></a-space></template></DataTable></div><a-modal v-model:open="modalVisible" :title="editingId?'编辑社团':'新建社团'" @ok="onSubmit"><a-form layout="vertical"><a-form-item label="名称" required><a-input v-model:value="form.name"/></a-form-item><a-form-item label="负责人ID" required><a-input v-model:value="form.leaderId"/></a-form-item><a-form-item label="描述"><a-textarea v-model:value="form.description"/></a-form-item></a-form></a-modal></div></template>
<script setup lang="ts">import {ref,reactive} from 'vue';import {message,Modal} from 'ant-design-vue';import {clubApi} from '@/api/club';import FilterBar from '@/components/common/FilterBar.vue';import DataTable from '@/components/common/DataTable.vue'
const ld=ref(false),list=ref<any[]>([]),t=ref(0),p=ref(1),ps=ref(20);const f=reactive({keyword:'',status:undefined as string|undefined})
const cols=[{title:'ID',dataIndex:'id',width:80},{title:'封面',dataIndex:'cover',width:70,slot:'cover'},{title:'名称',dataIndex:'name',width:150},{title:'负责人',dataIndex:'leaderId',width:120},{title:'人数',dataIndex:'memberCount',width:80,slot:'memberCount'},{title:'状态',dataIndex:'status',width:80,slot:'status'},{title:'时间',dataIndex:'createdAt',width:160},{title:'操作',dataIndex:'action',width:180,slot:'a'}]
async function ft(){ld.value=true;try{const r=await clubApi.getClubList({page:p.value,pageSize:ps.value,...f});list.value=r.data.data?.list||r.data?.list||[];t.value=r.data.data?.total||r.data?.total||0}catch{}finally{ld.value=false}}
function onSearch(){p.value=1;ft()};function onReset(){f.keyword='';f.status=undefined;onSearch()}
const modalVisible=ref(false),editingId=ref(''),form=reactive({name:'',leaderId:'',description:''})
function onCreate(){editingId.value='';form.name='';form.leaderId='';form.description='';modalVisible.value=true}
function onEdit(r:any){editingId.value=r.id;form.name=r.name;form.leaderId=r.leaderId;form.description=r.description||'';modalVisible.value=true}
async function onSubmit(){const data={...form};if(editingId.value){await clubApi.updateClub(editingId.value,data)}else{await clubApi.createClub(data)}message.success('保存成功');modalVisible.value=false;ft()}
async function onToggle(r:any){const ns=r.status==='active'?'banned':'active';await clubApi.updateClubStatus(r.id,ns);message.success('已更新');ft()}
async function onDelete(r:any){Modal.confirm({title:'确认删除',content:`确定删除「${r.name}」吗？`,onOk:async()=>{await clubApi.deleteClub(r.id);message.success('已删除');ft()}})}
ft();
</script>
