<template><div class="page-container"><FilterBar @search="onSearch" @reset="onReset"><a-select v-model:value="f.status" placeholder="状态" allow-clear style="width:120px"><a-select-option value="active">进行中</a-select-option><a-select-option value="drawn">已开奖</a-select-option><a-select-option value="cancelled">已取消</a-select-option></a-select></FilterBar><div class="page-card"><DataTable :columns="cols" :data-source="list" :loading="ld" :total="t" v-model:page="p" v-model:page-size="ps"><template #drawAt="{r}">{{r.drawAt?.replace('T',' ').slice(0,16)}}</template><template #status="{r}"><StatusTag :status="r.status" type="general"/></template><template #a="{r}"><a-space><a @click="$router.push('/lottery/winners/'+r.id)">中奖记录</a><a @click="onDelete(r)" style="color:#ff4d4f">删除</a></a-space></template></DataTable></div></div></template>
<script setup lang="ts">import {ref,reactive} from 'vue';import {message,Modal} from 'ant-design-vue';import {lotteryApi} from '@/api/lottery';import FilterBar from '@/components/common/FilterBar.vue';import DataTable from '@/components/common/DataTable.vue';import StatusTag from '@/components/common/StatusTag.vue'
const ld=ref(false),list=ref<any[]>([]),t=ref(0),p=ref(1),ps=ref(20);const f=reactive({status:undefined as string|undefined})
const cols=[{title:'ID',dataIndex:'id',width:80},{title:'标题',dataIndex:'title',width:200},{title:'开奖时间',dataIndex:'drawAt',width:160,slot:'drawAt'},{title:'允许重复',dataIndex:'allowDuplicate',width:90,format:(v:any)=>v?'是':'否'},{title:'奖品数',dataIndex:'prizes',width:80,format:(v:any)=>v?.length||0},{title:'中奖人数',dataIndex:'_count',width:80,format:(v:any)=>v?.winners||0},{title:'状态',dataIndex:'status',width:90,slot:'status'},{title:'时间',dataIndex:'createdAt',width:160},{title:'操作',dataIndex:'action',width:140,slot:'a'}]
async function ft(){ld.value=true;try{const r=await lotteryApi.getLotteryList({page:p.value,pageSize:ps.value,...f});list.value=r.data.data?.list||r.data?.list||[];t.value=r.data.data?.total||r.data?.total||0}catch{}finally{ld.value=false}}
function onSearch(){p.value=1;ft()};function onReset(){f.status=undefined;onSearch()}
async function onDelete(r:any){Modal.confirm({title:'确认删除',content:`确定删除「${r.title}」吗？`,onOk:async()=>{await lotteryApi.deleteLottery(r.id);message.success('已删除');ft()}})}
ft();
</script>
