ALTER TYPE "SecondHandStatus" ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE "SecondHandStatus" ADD VALUE IF NOT EXISTS 'REJECTED';

ALTER TABLE "second_hands"
  ADD COLUMN IF NOT EXISTS "deliveryType" TEXT NOT NULL DEFAULT '线下交易',
  ADD COLUMN IF NOT EXISTS "tags" JSONB,
  ADD COLUMN IF NOT EXISTS "location" JSONB,
  ADD COLUMN IF NOT EXISTS "freight" DECIMAL(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "wantCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "auditReason" TEXT;

ALTER TABLE "second_hand_orders"
  ADD COLUMN IF NOT EXISTS "shippingAddress" JSONB,
  ADD COLUMN IF NOT EXISTS "remark" TEXT,
  ADD COLUMN IF NOT EXISTS "paymentNo" TEXT;

ALTER TABLE "second_hand_region_settings"
  ADD COLUMN IF NOT EXISTS "enableOnlinePayment" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "enableAfterSale" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "enablePlatformGuarantee" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "enableAutoRecommend" BOOLEAN NOT NULL DEFAULT false;
