<template><div class="page-container"><div class="page-card"><div class="page-header"><span class="page-title">系统通知</span><a-button type="primary" @click="onCreate"><plus-outlined/>新建通知</a-button></div><DataTable :columns="cols" :data-source="list" :loading="ld" :total="t" v-model:page="p" v-model:page-size="ps"><template #sendStatus="{r}"><a-tag :color="r.sendStatus==='sent'?'green':r.sendStatus==='sending'?'processing':'default'">{{r.sendStatus==='sent'?'已发送':r.sendStatus==='sending'?'发送中':'草稿'}}</a-tag></template><template #a="{r}"><a-space><a @click="onEdit(r)">编辑</a><a v-if="r.sendStatus==='draft'" @click="onSend(r)" style="color:#10b981">发送</a><a-popconfirm title="确定删除?" @confirm="onDel(r.id)"><a style="color:#ef4444">删除</a></a-popconfirm></a-space></template></DataTable></div></div></template>
<script setup lang="ts">import {ref} from 'vue';import {message} from 'ant-design-vue';import {PlusOutlined} from '@ant-design/icons-vue';import {marketingApi} from '@/api/marketing';import DataTable from '@/components/common/DataTable.vue'
const ld=ref(false),list=ref<any[]>([]),t=ref(0),p=ref(1),ps=ref(20);const cols=[{title:'标题',dataIndex:'title',width:200},{title:'类型',dataIndex:'type',width:80},{title:'目标',dataIndex:'targetType',width:80},{title:'发送状态',dataIndex:'sendStatus',width:90,slot:'sendStatus'},{title:'阅读',dataIndex:'readCount',width:60},{title:'总量',dataIndex:'totalCount',width:60},{title:'时间',dataIndex:'createdAt',width:160},{title:'操作',dataIndex:'action',width:180,slot:'a'}]
async function ft(){ld.value=true;try{const r=await marketingApi.getNotificationList({page:p.value,pageSize:ps.value});list.value=r.data.data?.list||r.data?.list||[];t.value=r.data.data?.total||0}catch{}finally{ld.value=false}}
function onCreate(){message.info('新建通知')};function onEdit(_:any){message.info('编辑')}
async function onSend(r:any){await marketingApi.sendNotification(r.id);message.success('已发送');ft()}
async function onDel(id:number){await marketingApi.deleteNotification(id);message.success('已删除');ft()}
ft();
</script>
