<template><div class="page-container"><FilterBar @search="onSearch" @reset="onReset"><a-input v-model:value="f.keyword" placeholder="标题" allow-clear style="width:180px"/></FilterBar><div class="page-card"><div class="page-header"><span class="page-title">用户引导页</span><a-button type="primary" @click="onCreate">新建引导页</a-button></div><DataTable :columns="cols" :data-source="list" :loading="ld" :total="t" v-model:page="p" v-model:page-size="ps"><template #status="{r}"><a-tag :color="r.isShow?'green':'default'">{{r.isShow?'显示':'隐藏'}}</a-tag></template><template #a="{r}"><a-space><a @click="onEdit(r)">编辑</a><a @click="onDelete(r)" style="color:#ff4d4f">删除</a></a-space></template></DataTable></div><a-modal v-model:open="modalVisible" :title="editingId?'编辑引导页':'新建引导页'" @ok="onSubmit"><a-form layout="vertical"><a-form-item label="标题" required><a-input v-model:value="form.title"/></a-form-item><a-form-item label="类型"><a-select v-model:value="form.type"><a-select-option value="guide">引导</a-select-option><a-select-option value="popup">弹窗</a-select-option><a-select-option value="banner">横幅</a-select-option></a-select></a-form-item><a-form-item label="区域ID"><a-input v-model:value="form.regionId"/></a-form-item><a-form-item label="内容"><a-textarea v-model:value="form.content" :rows="4"/></a-form-item><a-form-item label="排序"><a-input-number v-model:value="form.sortOrder"/></a-form-item></a-form></a-modal></div></template>
<script setup lang="ts">import {ref,reactive} from 'vue';import {message,Modal} from 'ant-design-vue';import {userGuidanceApi} from '@/api/userGuidance';import FilterBar from '@/components/common/FilterBar.vue';import DataTable from '@/components/common/DataTable.vue'
const ld=ref(false),list=ref<any[]>([]),t=ref(0),p=ref(1),ps=ref(20);const f=reactive({keyword:''})
const cols=[{title:'ID',dataIndex:'id',width:80},{title:'标题',dataIndex:'title',width:200},{title:'类型',dataIndex:'type',width:80},{title:'排序',dataIndex:'sortOrder',width:70},{title:'状态',dataIndex:'isShow',width:80,slot:'status'},{title:'时间',dataIndex:'createdAt',width:160},{title:'操作',dataIndex:'action',width:120,slot:'a'}]
async function ft(){ld.value=true;try{const r=await userGuidanceApi.getList({page:p.value,pageSize:ps.value,...f});list.value=r.data.data?.list||r.data?.list||[];t.value=r.data.data?.total||r.data?.total||0}catch{}finally{ld.value=false}}
function onSearch(){p.value=1;ft()};function onReset(){f.keyword='';onSearch()}
const modalVisible=ref(false),editingId=ref(''),form=reactive({title:'',type:'guide',regionId:'',content:'',sortOrder:0})
function onCreate(){editingId.value='';form.title='';form.type='guide';form.regionId='';form.content='';form.sortOrder=0;modalVisible.value=true}
function onEdit(r:any){editingId.value=r.id;form.title=r.title;form.type=r.type;form.regionId=r.regionId;form.content=r.content;form.sortOrder=r.sortOrder;modalVisible.value=true}
async function onSubmit(){const data={...form};if(editingId.value){await userGuidanceApi.update(editingId.value,data)}else{await userGuidanceApi.create(data)}message.success('保存成功');modalVisible.value=false;ft()}
async function onDelete(r:any){Modal.confirm({title:'确认删除',content:`确定删除「${r.title}」吗？`,onOk:async()=>{await userGuidanceApi.delete(r.id);message.success('已删除');ft()}})}
ft();
</script>
