<template><div class="page-container"><FilterBar @search="onSearch" @reset="onReset"><a-input v-model:value="f.keyword" placeholder="商品名称" allow-clear style="width:180px"/><a-select v-model:value="f.status" placeholder="状态" allow-clear style="width:110px"><a-select-option value="on">上架</a-select-option><a-select-option value="off">下架</a-select-option></a-select></FilterBar><div class="page-card"><DataTable :columns="cols" :data-source="list" :loading="ld" :total="t" v-model:page="p" v-model:page-size="ps"><template #cover="{r}"><a-image :src="r.coverImage" :width="50" :height="50" style="object-fit:cover;border-radius:4px"/></template><template #minPrice="{r}">{{(r.minPrice/100).toFixed(2)}}</template><template #status="{r}"><StatusTag :status="r.status" type="general"/></template><template #a="{r}"><a-space><a @click="$router.push('/shop/product/'+r.id)">详情</a><a @click="onToggle(r)">{{r.status==='on'?'下架':'上架'}}</a></a-space></template></DataTable></div></div></template>
<script setup lang="ts">import {ref,reactive} from 'vue';import {message} from 'ant-design-vue';import {shopApi} from '@/api/shop';import FilterBar from '@/components/common/FilterBar.vue';import DataTable from '@/components/common/DataTable.vue';import StatusTag from '@/components/common/StatusTag.vue'
const ld=ref(false),list=ref<any[]>([]),t=ref(0),p=ref(1),ps=ref(20);const f=reactive({keyword:'',status:undefined as string|undefined})
const cols=[{title:'封面',dataIndex:'coverImage',width:70,slot:'cover'},{title:'名称',dataIndex:'name',width:200},{title:'商家',dataIndex:'merchantName',width:120},{title:'类目',dataIndex:'categoryName',width:100},{title:'最低价',dataIndex:'minPrice',width:80,slot:'minPrice'},{title:'库存',dataIndex:'totalStock',width:70},{title:'销量',dataIndex:'totalSales',width:70},{title:'状态',dataIndex:'status',width:70,slot:'status'},{title:'时间',dataIndex:'createdAt',width:160},{title:'操作',dataIndex:'action',width:100,slot:'a'}]
async function ft(){ld.value=true;try{const r=await shopApi.getProductList({page:p.value,pageSize:ps.value,...f});list.value=r.data.data.list;t.value=r.data.data.total}catch{}finally{ld.value=false}}
function onSearch(){p.value=1;ft()};function onReset(){f.keyword='';f.status=undefined;onSearch()}
async function onToggle(r:any){await shopApi.toggleProductStatus(r.id,r.status==='on'?'off':'on');message.success('已更新');ft()}
ft();
</script>
