<template><div class="page-container"><FilterBar @search="onSearch" @reset="onReset"><a-select v-model:value="f.status" placeholder="状态" allow-clear style="width:120px"><a-select-option value="pending">待处理</a-select-option><a-select-option value="completed">已完成</a-select-option></a-select></FilterBar><div class="page-card"><DataTable :columns="cols" :data-source="list" :loading="ld" :total="t" v-model:page="p" v-model:page-size="ps"><template #amount="{r}">{{(r.amount/100).toFixed(2)}}</template><template #status="{r}"><StatusTag :status="r.status" type="audit"/></template><template #a="{r}"><template v-if="r.status==='pending'"><a-space><a @click="onA(r,'approve')" style="color:#10b981">通过</a><a @click="onA(r,'reject')" style="color:#ef4444">拒绝</a></a-space></template><span v-else style="color:#9ca3af">-</span></template></DataTable></div></div></template>
<script setup lang="ts">import {ref,reactive} from 'vue';import {message} from 'ant-design-vue';import {shopApi} from '@/api/shop';import FilterBar from '@/components/common/FilterBar.vue';import DataTable from '@/components/common/DataTable.vue';import StatusTag from '@/components/common/StatusTag.vue'
const ld=ref(false),list=ref<any[]>([]),t=ref(0),p=ref(1),ps=ref(20);const f=reactive({status:undefined as string|undefined})
const cols=[{title:'订单号',dataIndex:'orderNo',width:180},{title:'用户',dataIndex:'userNickname',width:100},{title:'金额',dataIndex:'amount',width:90,slot:'amount'},{title:'原因',dataIndex:'reason',width:150},{title:'状态',dataIndex:'status',width:80,slot:'status'},{title:'时间',dataIndex:'createdAt',width:160},{title:'操作',dataIndex:'action',width:120,slot:'a'}]
async function ft(){ld.value=true;try{const r=await shopApi.getRefundList({page:p.value,pageSize:ps.value,...f});list.value=r.data.data.list;t.value=r.data.data.total}catch{}finally{ld.value=false}}
function onSearch(){p.value=1;ft()};function onReset(){f.status=undefined;onSearch()}
async function onA(r:any,a:'approve'|'reject'){if(a==='approve')await shopApi.approveRefund(r.id);else await shopApi.rejectRefund(r.id,'');message.success('已处理');ft()}
ft();
</script>
