CREATE TABLE IF NOT EXISTS `campus_map_projects` (
  `id` VARCHAR(191) NOT NULL,
  `officialNumber` INTEGER NOT NULL,
  `officialName` VARCHAR(191) NOT NULL,
  `engineeringAlias` VARCHAR(191) NOT NULL DEFAULT '',
  `phase` VARCHAR(191) NOT NULL DEFAULT 'phase1',
  `constructionStatus` VARCHAR(191) NOT NULL DEFAULT 'built',
  `visibilityScope` VARCHAR(191) NOT NULL DEFAULT 'phase1_review',
  `semanticType` VARCHAR(191) NOT NULL DEFAULT 'building',
  `searchable` BOOLEAN NOT NULL DEFAULT false,
  `navigable` BOOLEAN NOT NULL DEFAULT false,
  `geometryStatus` VARCHAR(191) NOT NULL DEFAULT 'unmatched',
  `sourceConfidence` VARCHAR(191) NOT NULL DEFAULT 'official_signage_only',
  `photos` JSON NOT NULL,
  `notes` TEXT NULL,
  `sortOrder` INTEGER NOT NULL DEFAULT 0,
  `createdBy` VARCHAR(191) NULL,
  `updatedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `campus_map_projects_officialNumber_key` (`officialNumber`),
  INDEX `campus_map_projects_officialNumber_idx` (`officialNumber`),
  INDEX `campus_map_projects_constructionStatus_visibilityScope_idx` (`constructionStatus`, `visibilityScope`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
