<template><div class="page-container"><FilterBar @search="onSearch" @reset="onReset"><a-input v-model:value="f.keyword" placeholder="头衔名称" allow-clear style="width:180px"/><a-select v-model:value="f.type" placeholder="类型" allow-clear style="width:110px"><a-select-option value="badge">徽章</a-select-option><a-select-option value="title">称号</a-select-option></a-select></FilterBar><div class="page-card"><div class="page-header"><span class="page-title">头衔管理</span><a-button type="primary" @click="onCreate">新建头衔</a-button></div><DataTable :columns="cols" :data-source="list" :loading="ld" :total="t" v-model:page="p" v-model:page-size="ps"><template #icon="{r}"><a-image v-if="r.icon" :src="r.icon" :width="40" :height="40" style="object-fit:cover;border-radius:4px"/><span v-else>-</span></template><template #records="{r}">{{r._count?.records||0}}</template><template #a="{r}"><a-space><a @click="$router.push('/user-title/redeem-codes/'+r.id)">兑换码</a><a @click="onEdit(r)">编辑</a><a @click="onDelete(r)" style="color:#ff4d4f">删除</a></a-space></template></DataTable></div><a-modal v-model:open="modalVisible" :title="editingId?'编辑头衔':'新建头衔'" @ok="onSubmit"><a-form layout="vertical"><a-form-item label="名称" required><a-input v-model:value="form.name"/></a-form-item><a-form-item label="类型"><a-select v-model:value="form.type"><a-select-option value="badge">徽章</a-select-option><a-select-option value="title">称号</a-select-option></a-select></a-form-item><a-form-item label="图标"><a-input v-model:value="form.icon"/></a-form-item><a-form-item label="描述"><a-input v-model:value="form.description"/></a-form-item><a-form-item label="获取条件"><a-input v-model:value="form.condition"/></a-form-item><a-form-item label="排序"><a-input-number v-model:value="form.sortOrder"/></a-form-item></a-form></a-modal></div></template>
<script setup lang="ts">import {ref,reactive} from 'vue';import {message,Modal} from 'ant-design-vue';import {userTitleApi} from '@/api/userTitle';import FilterBar from '@/components/common/FilterBar.vue';import DataTable from '@/components/common/DataTable.vue'
const ld=ref(false),list=ref<any[]>([]),t=ref(0),p=ref(1),ps=ref(20);const f=reactive({keyword:'',type:undefined as string|undefined})
const cols=[{title:'ID',dataIndex:'id',width:80},{title:'图标',dataIndex:'icon',width:60,slot:'icon'},{title:'名称',dataIndex:'name',width:150},{title:'类型',dataIndex:'type',width:80},{title:'领取人数',dataIndex:'_count',width:80,slot:'records'},{title:'排序',dataIndex:'sortOrder',width:70},{title:'时间',dataIndex:'createdAt',width:160},{title:'操作',dataIndex:'action',width:180,slot:'a'}]
async function ft(){ld.value=true;try{const r=await userTitleApi.getList({page:p.value,pageSize:ps.value,...f});list.value=r.data.data?.list||r.data?.list||[];t.value=r.data.data?.total||r.data?.total||0}catch{}finally{ld.value=false}}
function onSearch(){p.value=1;ft()};function onReset(){f.keyword='';f.type=undefined;onSearch()}
const modalVisible=ref(false),editingId=ref(''),form=reactive({name:'',type:'badge',icon:'',description:'',condition:'',sortOrder:0})
function onCreate(){editingId.value='';form.name='';form.type='badge';form.icon='';form.description='';form.condition='';form.sortOrder=0;modalVisible.value=true}
function onEdit(r:any){editingId.value=r.id;form.name=r.name;form.type=r.type;form.icon=r.icon||'';form.description=r.description||'';form.condition=r.condition||'';form.sortOrder=r.sortOrder;modalVisible.value=true}
async function onSubmit(){const data={...form};if(editingId.value){await userTitleApi.update(editingId.value,data)}else{await userTitleApi.create(data)}message.success('保存成功');modalVisible.value=false;ft()}
async function onDelete(r:any){Modal.confirm({title:'确认删除',content:`确定删除「${r.name}」吗？`,onOk:async()=>{await userTitleApi.delete(r.id);message.success('已删除');ft()}})}
ft();
</script>
