<template><div class="page-container"><FilterBar @search="onSearch" @reset="onReset"><a-input v-model:value="f.sn" placeholder="设备编号" allow-clear style="width:180px"/><a-select v-model:value="f.status" placeholder="状态" allow-clear style="width:110px"><a-select-option value="active">正常</a-select-option><a-select-option value="inactive">停用</a-select-option></a-select></FilterBar><div class="page-card"><DataTable :columns="cols" :data-source="list" :loading="ld" :total="t" v-model:page="p" v-model:page-size="ps"><template #status="{r}"><a-tag :color="r.status==='active'?'green':'default'">{{r.status==='active'?'正常':'停用'}}</a-tag></template><template #a="{r}"><a-space><a @click="onToggle(r)">{{r.status==='active'?'停用':'启用'}}</a><a @click="onDelete(r)" style="color:#ff4d4f">删除</a></a-space></template></DataTable></div></div></template>
<script setup lang="ts">import {ref,reactive} from 'vue';import {message,Modal} from 'ant-design-vue';import {printerApi} from '@/api/printer';import FilterBar from '@/components/common/FilterBar.vue';import DataTable from '@/components/common/DataTable.vue'
const ld=ref(false),list=ref<any[]>([]),t=ref(0),p=ref(1),ps=ref(20);const f=reactive({sn:'',status:undefined as string|undefined})
const cols=[{title:'ID',dataIndex:'id',width:80},{title:'名称',dataIndex:'name',width:120},{title:'品牌',dataIndex:'brand',width:80},{title:'编号',dataIndex:'sn',width:150},{title:'商家ID',dataIndex:'merchantId',width:120},{title:'自动打印',dataIndex:'autoPrint',width:90,format:(v:any)=>v?'是':'否'},{title:'状态',dataIndex:'status',width:80,slot:'status'},{title:'时间',dataIndex:'createdAt',width:160},{title:'操作',dataIndex:'action',width:130,slot:'a'}]
async function ft(){ld.value=true;try{const r=await printerApi.getList({page:p.value,pageSize:ps.value,...f});list.value=r.data.data?.list||r.data?.list||[];t.value=r.data.data?.total||r.data?.total||0}catch{}finally{ld.value=false}}
function onSearch(){p.value=1;ft()};function onReset(){f.sn='';f.status=undefined;onSearch()}
async function onToggle(r:any){const ns=r.status==='active'?'inactive':'active';await printerApi.updateStatus(r.id,ns);message.success('已更新');ft()}
async function onDelete(r:any){Modal.confirm({title:'确认删除',content:`确定删除「${r.name}」吗？`,onOk:async()=>{await printerApi.delete(r.id);message.success('已删除');ft()}})}
ft();
</script>
