<template><div class="page-container"><FilterBar @search="onSearch" @reset="onReset"><a-input v-model:value="f.keyword" placeholder="内容/用户" allow-clear style="width:180px"/><a-select v-model:value="f.rating" placeholder="评分" allow-clear style="width:100px"><a-select-option :value="5">5星</a-select-option><a-select-option :value="4">4星</a-select-option><a-select-option :value="3">3星</a-select-option><a-select-option :value="2">2星</a-select-option><a-select-option :value="1">1星</a-select-option></a-select></FilterBar><div class="page-card"><DataTable :columns="cols" :data-source="list" :loading="ld" :total="t" v-model:page="p" v-model:page-size="ps"><template #rating="{r}"><a-rate :value="r.rating" disabled/></template><template #status="{r}"><a-tag :color="r.status?'green':'red'">{{r.status?'正常':'屏蔽'}}</a-tag></template><template #a="{r}"><a-space><a @click="onReply(r)">回复</a><a @click="onDelete(r)" style="color:#ff4d4f">删除</a></a-space></template></DataTable></div><a-modal v-model:open="replyVisible" title="回复评价" @ok="onSubmitReply"><a-textarea v-model:value="replyText" :rows="4"/></a-modal></div></template>
<script setup lang="ts">import {ref,reactive} from 'vue';import {message,Modal} from 'ant-design-vue';import {shopApi} from '@/api/shop';import FilterBar from '@/components/common/FilterBar.vue';import DataTable from '@/components/common/DataTable.vue'
const ld=ref(false),list=ref<any[]>([]),t=ref(0),p=ref(1),ps=ref(20);const f=reactive({keyword:'',rating:undefined as number|undefined})
const cols=[{title:'ID',dataIndex:'id',width:70},{title:'用户',dataIndex:'userNickname',width:120},{title:'评分',dataIndex:'rating',width:120,slot:'rating'},{title:'内容',dataIndex:'content',width:250,format:(v:any)=>(v||'').slice(0,40)},{title:'商家回复',dataIndex:'merchantReply',width:150,format:(v:any)=>(v||'').slice(0,20)||'-'},{title:'状态',dataIndex:'status',width:80,slot:'status'},{title:'时间',dataIndex:'createdAt',width:160},{title:'操作',dataIndex:'action',width:120,slot:'a'}]
async function ft(){ld.value=true;try{const r=await shopApi.getReviewList({page:p.value,pageSize:ps.value,...f});list.value=r.data.data?.list||r.data?.list||[];t.value=r.data.data?.total||r.data?.total||0}catch{}finally{ld.value=false}}
function onSearch(){p.value=1;ft()};function onReset(){f.keyword='';f.rating=undefined;onSearch()}
const replyVisible=ref(false),replyId=ref(''),replyText=ref('')
function onReply(r:any){replyId.value=r.id;replyText.value=r.merchantReply||'';replyVisible.value=true}
async function onSubmitReply(){await shopApi.replyReview(+replyId.value,replyText.value);message.success('回复成功');replyVisible.value=false;ft()}
async function onDelete(r:any){Modal.confirm({title:'确认删除',content:'确定删除该评价吗？',onOk:async()=>{await shopApi.deleteReview(+r.id);message.success('已删除');ft()}})}
ft();
</script>
