<template><div class="page-container"><FilterBar @search="onSearch" @reset="onReset"><a-select v-model:value="f.categoryId" placeholder="分类" allow-clear style="width:140px"><a-select-option v-for="c in categories" :key="c.id" :value="c.id">{{c.name}}</a-select-option></a-select><a-select v-model:value="f.status" placeholder="状态" allow-clear style="width:110px"><a-select-option value="active">正常</a-select-option><a-select-option value="banned">封禁</a-select-option></a-select></FilterBar><div class="page-card"><DataTable :columns="cols" :data-source="list" :loading="ld" :total="t" v-model:page="p" v-model:page-size="ps"><template #url="{r}"><a-image :src="r.url" :width="50" :height="50" style="object-fit:cover;border-radius:4px"/></template><template #status="{r}"><a-tag :color="r.status==='active'?'green':'red'">{{r.status==='active'?'正常':'封禁'}}</a-tag></template><template #a="{r}"><a-space><a @click="onToggle(r)">{{r.status==='active'?'封禁':'解封'}}</a><a @click="onDelete(r)" style="color:#ff4d4f">删除</a></a-space></template></DataTable></div></div></template>
<script setup lang="ts">import {ref,reactive} from 'vue';import {message,Modal} from 'ant-design-vue';import {stickerApi} from '@/api/sticker';import FilterBar from '@/components/common/FilterBar.vue';import DataTable from '@/components/common/DataTable.vue'
const ld=ref(false),list=ref<any[]>([]),t=ref(0),p=ref(1),ps=ref(20);const f=reactive({categoryId:undefined as string|undefined,status:undefined as string|undefined})
const categories=ref<any[]>([])
const cols=[{title:'ID',dataIndex:'id',width:80},{title:'贴纸',dataIndex:'url',width:70,slot:'url'},{title:'名称',dataIndex:'name',width:150},{title:'分类',dataIndex:'categoryName',width:100},{title:'用户',dataIndex:'userName',width:120},{title:'状态',dataIndex:'status',width:80,slot:'status'},{title:'时间',dataIndex:'createdAt',width:160},{title:'操作',dataIndex:'action',width:140,slot:'a'}]
async function ft(){ld.value=true;try{const r=await stickerApi.getStickerList({page:p.value,pageSize:ps.value,...f});list.value=r.data.data?.list||r.data?.list||[];t.value=r.data.data?.total||r.data?.total||0}catch{}finally{ld.value=false}}
async function fc(){const r=await stickerApi.getCategoryList({page:1,pageSize:100});categories.value=r.data.data?.list||r.data?.list||[]}
function onSearch(){p.value=1;ft()};function onReset(){f.categoryId=undefined;f.status=undefined;onSearch()}
async function onToggle(r:any){const ns=r.status==='active'?'banned':'active';await stickerApi.updateStatus(r.id,ns);message.success('已更新');ft()}
async function onDelete(r:any){Modal.confirm({title:'确认删除',content:`确定删除「${r.name}」吗？`,onOk:async()=>{await stickerApi.delete(r.id);message.success('已删除');ft()}})}
ft();fc();
</script>
