<template><div class="page-container"><div class="page-card"><div class="page-header"><span class="page-title">充值套餐</span><a-button type="primary" @click="onCreate">新建套餐</a-button></div><DataTable :columns="cols" :data-source="list" :loading="ld" :total="t" v-model:page="p" v-model:page-size="ps"><template #amount="{r}">{{(+r.amount).toFixed(2)}}</template><template #giveAmount="{r}">{{(+r.giveAmount).toFixed(2)}}</template><template #a="{r}"><a-space><a @click="onEdit(r)">编辑</a><a @click="onDelete(r)" style="color:#ff4d4f">删除</a></a-space></template></DataTable></div><a-modal v-model:open="modalVisible" :title="editingId?'编辑套餐':'新建套餐'" @ok="onSubmit"><a-form layout="vertical"><a-form-item label="名称" required><a-input v-model:value="form.name"/></a-form-item><a-form-item label="金额" required><a-input-number v-model:value="form.amount"/></a-form-item><a-form-item label="赠送金额"><a-input-number v-model:value="form.giveAmount"/></a-form-item><a-form-item label="排序"><a-input-number v-model:value="form.sortOrder"/></a-form-item></a-form></a-modal></div></template>
<script setup lang="ts">import {ref,reactive} from 'vue';import {message,Modal} from 'ant-design-vue';import {topupApi} from '@/api/topup';import DataTable from '@/components/common/DataTable.vue'
const ld=ref(false),list=ref<any[]>([]),t=ref(0),p=ref(1),ps=ref(20)
const cols=[{title:'ID',dataIndex:'id',width:80},{title:'名称',dataIndex:'name',width:150},{title:'金额',dataIndex:'amount',width:90,slot:'amount'},{title:'赠送',dataIndex:'giveAmount',width:90,slot:'giveAmount'},{title:'排序',dataIndex:'sortOrder',width:70},{title:'时间',dataIndex:'createdAt',width:160},{title:'操作',dataIndex:'action',width:120,slot:'a'}]
async function ft(){ld.value=true;try{const r=await topupApi.getPackageList({page:p.value,pageSize:ps.value});list.value=r.data.data?.list||r.data?.list||[];t.value=r.data.data?.total||r.data?.total||0}catch{}finally{ld.value=false}}
const modalVisible=ref(false),editingId=ref(''),form=reactive({name:'',amount:0,giveAmount:0,sortOrder:0})
function onCreate(){editingId.value='';form.name='';form.amount=0;form.giveAmount=0;form.sortOrder=0;modalVisible.value=true}
function onEdit(r:any){editingId.value=r.id;form.name=r.name;form.amount=+r.amount;form.giveAmount=+r.giveAmount;form.sortOrder=r.sortOrder;modalVisible.value=true}
async function onSubmit(){const data={...form};if(editingId.value){await topupApi.updatePackage(editingId.value,data)}else{await topupApi.createPackage(data)}message.success('保存成功');modalVisible.value=false;ft()}
async function onDelete(r:any){Modal.confirm({title:'确认删除',content:`确定删除「${r.name}」吗？`,onOk:async()=>{await topupApi.deletePackage(r.id);message.success('已删除');ft()}})}
ft();
</script>
