/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AuditModal: typeof import('./../components/common/AuditModal.vue')['default']
    DataTable: typeof import('./../components/common/DataTable.vue')['default']
    DataTableCard: typeof import('./../components/glass/DataTableCard.vue')['default']
    DetailDrawer: typeof import('./../components/glass/DetailDrawer.vue')['default']
    FieldRender: typeof import('./../components/glass/FieldRender.vue')['default']
    FilterBar: typeof import('./../components/common/FilterBar.vue')['default']
    GlassPageHeader: typeof import('./../components/glass/GlassPageHeader.vue')['default']
    ImagePreview: typeof import('./../components/common/ImagePreview.vue')['default']
    MapPicker: typeof import('./../components/common/MapPicker.vue')['default']
    OperationLog: typeof import('./../components/common/OperationLog.vue')['default']
    OperationModulePage: typeof import('./../components/business/OperationModulePage.vue')['default']
    RichEditor: typeof import('./../components/common/RichEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPanel: typeof import('./../components/glass/SearchPanel.vue')['default']
    SidePanels: typeof import('./../components/glass/SidePanels.vue')['default']
    StatGrid: typeof import('./../components/glass/StatGrid.vue')['default']
    StatusTag: typeof import('./../components/common/StatusTag.vue')['default']
  }
}
