<template><div class="page-container"><FilterBar @search="onSearch" @reset="onReset"><a-select v-model:value="f.type" placeholder="类型" allow-clear style="width:120px"><a-select-option value="post">帖子榜</a-select-option><a-select-option value="user">用户榜</a-select-option><a-select-option value="merchant">商家榜</a-select-option><a-select-option value="rider">骑手榜</a-select-option></a-select><a-select v-model:value="f.period" placeholder="周期" allow-clear style="width:110px"><a-select-option value="day">日榜</a-select-option><a-select-option value="week">周榜</a-select-option><a-select-option value="month">月榜</a-select-option></a-select></FilterBar><div class="page-card"><div class="page-header"><span class="page-title">排行榜管理</span><a-button type="primary" @click="onCreate">新建榜单</a-button></div><DataTable :columns="cols" :data-source="list" :loading="ld" :total="t" v-model:page="p" v-model:page-size="ps"><template #a="{r}"><a-space><a @click="onEdit(r)">编辑</a><a @click="onDelete(r)" style="color:#ff4d4f">删除</a></a-space></template></DataTable></div><a-modal v-model:open="modalVisible" :title="editingId?'编辑榜单':'新建榜单'" @ok="onSubmit"><a-form layout="vertical"><a-form-item label="标题" required><a-input v-model:value="form.title"/></a-form-item><a-form-item label="类型" required><a-select v-model:value="form.type"><a-select-option value="post">帖子榜</a-select-option><a-select-option value="user">用户榜</a-select-option><a-select-option value="merchant">商家榜</a-select-option><a-select-option value="rider">骑手榜</a-select-option></a-select></a-form-item><a-form-item label="周期"><a-select v-model:value="form.period"><a-select-option value="day">日榜</a-select-option><a-select-option value="week">周榜</a-select-option><a-select-option value="month">月榜</a-select-option></a-select></a-form-item></a-form></a-modal></div></template>
<script setup lang="ts">import {ref,reactive} from 'vue';import {message,Modal} from 'ant-design-vue';import {rankingApi} from '@/api/ranking';import FilterBar from '@/components/common/FilterBar.vue';import DataTable from '@/components/common/DataTable.vue'
const ld=ref(false),list=ref<any[]>([]),t=ref(0),p=ref(1),ps=ref(20);const f=reactive({type:undefined as string|undefined,period:undefined as string|undefined})
const cols=[{title:'ID',dataIndex:'id',width:80},{title:'标题',dataIndex:'title',width:200},{title:'类型',dataIndex:'type',width:100},{title:'周期',dataIndex:'period',width:80},{title:'时间',dataIndex:'createdAt',width:160},{title:'操作',dataIndex:'action',width:120,slot:'a'}]
async function ft(){ld.value=true;try{const r=await rankingApi.getList({page:p.value,pageSize:ps.value,...f});list.value=r.data.data?.list||r.data?.list||[];t.value=r.data.data?.total||r.data?.total||0}catch{}finally{ld.value=false}}
function onSearch(){p.value=1;ft()};function onReset(){f.type=undefined;f.period=undefined;onSearch()}
const modalVisible=ref(false),editingId=ref(''),form=reactive({title:'',type:'post',period:'week'})
function onCreate(){editingId.value='';form.title='';form.type='post';form.period='week';modalVisible.value=true}
function onEdit(r:any){editingId.value=r.id;form.title=r.title;form.type=r.type;form.period=r.period;modalVisible.value=true}
async function onSubmit(){const data={...form};if(editingId.value){await rankingApi.update(editingId.value,data)}else{await rankingApi.create(data)}message.success('保存成功');modalVisible.value=false;ft()}
async function onDelete(r:any){Modal.confirm({title:'确认删除',content:`确定删除「${r.title}」吗？`,onOk:async()=>{await rankingApi.delete(r.id);message.success('已删除');ft()}})}
ft();
</script>
